### ISSUE TITLE
bounding_tile issue

### ISSUE THREAD

**Issue by oteph** [mapbox/mercantile#100]
> pip3 show mercantile
> Name: mercantile
> Version: 1.0.4

`bounding_tile` does not return the same tile that was used to create the bounding box.
```py
>>> tile = mercantile.Tile(x=69327, y=45014, z=17)
>>> bounds = mercantile.bounds(tile)
>>> mercantile.bounding_tile(*bounds)
Tile(x=2166, y=1406, z=12)
```
The documentation seems to indicate that the behavior described is unexpected: 

> Get the smallest tile containing a geographic bounding box

Questions:

Is this working as intended? 
Why is the zoom level so small?

**Comment by oteph** [comment]
So i tried checked if there is some error specific to the case where the bounds input to bounding_tile is equal to the bounding box of a tile.
```py
>>> >>> w,s,e,n = mercantile.bounds(tile)
>>> offset = 1e-13
>>> mercantile.bounding_tile(w+offset,s+offset,e-offset,n-offset)
Tile(x=69327, y=45014, z=17)
```
So this fixes the issue.
```py
>>> >>> w,s,e,n = mercantile.bounds(tile)
>>> offset = 1e-14
>>> mercantile.bounding_tile(w+offset,s+offset,e-offset,n-offset)
Tile(x=2166, y=1406, z=12)
```
And broken again.

**Comment by sgillies** [comment]
@oteph I've got a solution going on in #101. Take a look if you'd like?
