### ISSUE TITLE
Split bounding box in n parts

### ISSUE THREAD

**Issue by michelbio** [mapbox/mercantile#103]
Currently I'd like to divide an existing bounding box [s,w,n,e] + Zoom level in `n` equal parts. So say in 4 parts. Is this possible with mercantile? 

The goal is to divide the bounding box, in order to render (to image) each individual part and stitch back together after.

**Comment by sgillies** [comment]
There's no single API function to do this, but I don't see any blockers in the API. A few lines of math is all it would take.
