### ISSUE TITLE
Other projections

### ISSUE THREAD

**Issue by davidbrochart** [mapbox/mercantile#109]
Could mercantile add support for using projections supported by PROJ, or is it completely out of scope?

**Comment by davidbrochart** [comment]
I just came across this snippet of code: https://gist.github.com/gka/52ef3bf442bed80367f6
Maybe this is all that is needed?

**Comment by vincentsarago** [comment]
Hi @davidbrochart 
Mercantile was designed only for webmercator and it’s don’t think It will support other projection soon.

There are couple project that tries to support other projections:
- https://github.com/EOX-A/meintile
- https://github.com/DigitalGlobe/tiletanic
- https://github.com/developmentseed/morecantile

Disclaimer: I built morecantile

Mapproxy library also has support for other TMS grid.

**Comment by davidbrochart** [comment]
Thanks @vincentsarago.
I had a quick look, but it looks like none of these libraries work with PROJ projections?

**Comment by vincentsarago** [comment]
@davidbrochart yeah, speaking for morecantile, I'm working on supporting non-epsg projection right now but the TMS specs force the use of epgs code so it's not easy. I hope to have a solution this week end. 
Is there a specific projection you'd like support ?

**Comment by davidbrochart** [comment]
In the end I will need to support any CRS specified by https://github.com/kartena/Proj4Leaflet.

**Comment by sgillies** [comment]
Hi @davidbrochart. Other coordinate systems are outside this project's scope.
