### ISSUE TITLE
tile function and " Heuristic to find points straddling tiles."

### ISSUE THREAD

**Issue by fruttasecca** [mapbox/mercantile#112]
I am slightly confused by this snippet of code from **def tile(lng, lat, zoom, truncate=False)**,
and the similar one regarding ytile.

```python
        xtile_a = math.floor((x - EPSILON) * Z2)
        xtile_b = math.floor((x + EPSILON) * Z2)
        if xtile_a != xtile_b:
            xtile = int(xtile_b)
        else:
            xtile = int(xtile_a)
```

It seems to me that the value in xtile_b will be always used, and that calculating xitle_a can be disregarded, or is there some floating point issue I am not seeing?

**Comment by sgillies** [comment]
@fruttasecca indeed. We'll fix this in 1.1.5.
