### ISSUE TITLE
Get bounding-tiles from GeoJSON-like object in library

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mercantile#119]
There is a `mercantile.feature` function to return GeoJSON corresponding to a tile.

The reverse - get a tile / tiles from GeoJSON - does not seem to exist in the library but it does exist in the `bounding-tile` cli script:

https://github.com/mapbox/mercantile/blob/d00e29330663d2ca8dc1f4056f92194286250b38/mercantile/scripts/__init__.py#L354

The `mercantile.bounding_tile` function takes a bbox but not a GeoJSON-like object.

What's the reason for this? Should there be a library function going from a GeoJSON object to a bounding tile, since it's a common use case - so common that we already provide a cli script for it.

Thoughts? :thinking:

**Comment by sgillies** [comment]
@daniel-j-h no particular reason. I thought that a Python programmer would be able to get the bounds of a GeoJSON feature or collection in a few lines of code (no more than 7, see https://github.com/mapbox/mercantile/blob/d00e29330663d2ca8dc1f4056f92194286250b38/mercantile/scripts/__init__.py#L426-L432), whereas its a lot harder to do on the command line.

**Comment by daniel-j-h** [comment]
Ja and that's also what I'm doing, just that I'm copying these utilities around in my codebases a lot, so why not share it? :hugs:
