### ISSUE TITLE
Invalid tiles should not be representable - error on invalid tile cordinates

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mercantile#122]
At the moment there seem to be no sanity checks for invalid tiles.

The library functions working on those invalid tiles then might return unreasonable results.

For example

```py
>>> mercantile.ul(Tile(-100000,0,10))
LngLat(lng=-35336.25, lat=85.0511287798066)
```

We should make sure
- the x coordinate goes form 0 to 2^zoom - 1
- the y coordinate goes from 0 to 2^zoom - 1
- the z coordinate starts at 0

Related: https://github.com/mapbox/mercantile/issues/120

**Comment by daniel-j-h** [comment]
The example above shows garbage in, garbage out, but I've found another one where we produce an invalid tile

```py
>>> mercantile.parent(mercantile.Tile(0,0,0))
Tile(x=0, y=0, z=-1)
```

on zoom level 0 there is exactly one tile; parent should then either return `None` or throw an exception but not produce an invalid tile.

It looks like the Tile type is simply defined as a namedtuple; ideally we'd check a tile's pre-conditions (valid x,y,z coordinates) in its constructor and throw on error. Then invalid tiles can not be represented. Thoughts?

**Comment by sgillies** [comment]
@daniel-j-h I'm a bit worried about violating Hyrum's Law here :sweat_smile: 

@vincentsarago @dnomadb @youngpm any of you relying on mercantile being able to represent invalid tiles?

**Comment by youngpm** [comment]
I hope not!  The dateline is a scourge on my life.

**Comment by daniel-j-h** [comment]
> @daniel-j-h I'm a bit worried about violating Hyrum's Law here sweat_smile

Gotcha :+1: Should we then at least provide some sort of validation function users can and should use?

And ticket a proper pre-condition validating constructor for v2?
