### ISSUE TITLE
`mercantile.parent` missing from API docs

### ISSUE THREAD

**Issue by kylebarron** [mapbox/mercantile#135]
I was just referring back to the documentation and I noticed `mercantile.parent` was missing from the [API docs page](https://mercantile.readthedocs.io/en/latest/api/mercantile.html). I thought I'd seen it there previously, and it looks like `parent` is still in the code on `main`, so thought I'd ask.

**Comment by sgillies** [comment]
Hmm, I must have left something invalid in the docstring?

**Comment by sgillies** [comment]
Missing comma after https://github.com/mapbox/mercantile/blob/main/mercantile/__init__.py#L43. 1.2.1 coming up!

**Comment by sgillies** [comment]
Fixed in d62250e.

**Comment by kylebarron** [comment]
Ah I've definitely been bitten by similar bugs! Thanks for your help!
