### ISSUE TITLE
add breaking changes in changelog 

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/mercantile#138]
https://github.com/mapbox/mercantile/pull/129 introduced a `breaking change` by moving `mercantile.scripts.coords` to `mercantile._coords`. 

I think it's acceptable to have breaking change between 1.1 and 1.2 but I think it's important to at least mention it in the changelog. 

@sgillies no harm here, I'm maybe the only one which import stuff from `scripts` code 🙈 

ref: https://github.com/developmentseed/morecantile/issues/50

**Comment by sgillies** [comment]
Sorry about that @vincentsarago . I didn't consider mercantile.scripts.coords to be part of the public API, but didn't mark it "private", either.

**Comment by vincentsarago** [comment]
as I said, it's ok I probably should stop using `script` functions 😂
