### ISSUE TITLE
Add support for quadkey/tile conversions

### ISSUE THREAD

**Issue by youngpm** [mapbox/mercantile#50]
I'm in need of a handy way to to convert back and forth from quadkeys and tiles like you can see [here](http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/).

PR on its way!

**Comment by sgillies** [comment]
@youngpm Great! It's a feature from https://github.com/mapbox/tilebelt#features that I've also wanted.

**Comment by sgillies** [comment]
Closed via #51
