### ISSUE TITLE
Mercantile CLI "tiles" errors when given GeoJSON with whitespace as an input

### ISSUE THREAD

**Issue by drewbo** [mapbox/mercantile#64]
This command succeeds:

```bash
$ echo "[106, 193, 9]" | mercantile shapes | mercantile tiles 10
[212, 386, 10]
[212, 387, 10]
[213, 386, 10]
[213, 387, 10]
```

This fails:

```bash
$ echo "[106, 193, 9]" | mercantile shapes --indent 2 | mercantile tiles 10
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```

For anyone coming across this error with GeoJSON "in the wild", my current workaround is to use `tr` to remove the whitespace:

```bash
$ echo "[106, 193, 9]" | mercantile shapes --indent 2 | tr -d " \t\n\r" | mercantile tiles 10
[212, 386, 10]
[212, 387, 10]
[213, 386, 10]
[213, 387, 10]
```

**Comment by sgillies** [comment]
@drewbo `jq -s -c` can work in some cases too.

```
$ echo "[106, 193, 9]" | mercantile shapes --indent 2 | jq -s -c '.[0]' | mercantile tiles 10
[212, 386, 10]
[212, 387, 10]
[213, 386, 10]
[213, 387, 10]
```

**Comment by drewbo** [comment]
@sgillies Cool. Do you have a preference on next steps? I think it could:
1. Remain as is and get a documentation update to clarify that it parses each line separately -- which has the side benefit of allowing nice uses like: 

```bash
$ echo "[106, 193, 9]\n[106, 194, 9]" | mercantile shapes | mercantile tiles 10
[212, 386, 10]
[212, 387, 10]
[213, 386, 10]
[213, 387, 10]
[212, 388, 10]
[212, 389, 10]
[213, 388, 10]
[213, 389, 10]
```
2. Or "slurp" the whole input

**Comment by sgillies** [comment]
@drewbo It's not a side benefit, this is a deliberate feature. Mercantile commands can take either

1. compact newline-delimited sequences of JSON
2. pretty-printed ASCII RS-delimited sequences of JSON (like https://tools.ietf.org/html/rfc8142 and https://tools.ietf.org/html/rfc7159)

But can't accept pretty-printed JSON without the RS.

I'm hesitant to support more kinds of input (your 2) as long as there are work-arounds (tr and jq). Limited slurping wouldn't be too complicated, yes? Read a single line and if `json.loads` fails, slurp in all lines and try again. I wouldn't, however, want this to expand to trying to slurp multiple non-delimited objects.

**Comment by drewbo** [comment]
Got it. I agree that it probably shouldn't support slurp and that leads down a tricky road. Is it worth adding those two input types to the cli docs?

**Comment by sgillies** [comment]
Update: turn on the `--seq` option of mercantile-shapes and then mercantile-tiles will understand how to read the output.

```
$ echo "[106, 193, 9]" | mercantile shapes --indent 2 --seq | mercantile tiles 10
[212, 386, 10]
[212, 387, 10]
[213, 386, 10]
[213, 387, 10]
```
