### ISSUE TITLE
Include full table of context in docs sidebar?

### ISSUE THREAD

**Issue by mapsam** [mapbox/mercantile#69]
Hey @sgillies! Love the docs for this project 🎉  

I was taking a peek and noticed the sidebar doesn't have the full table of contents, which makes navigating a tad bit difficult. Any chance they could be added? I've never used RTD before, so not sure how to go about doing this.

![mercantile-readthedocs](https://user-images.githubusercontent.com/1943001/32962124-228ab7d4-cb80-11e7-8fb1-aa4f060db682.gif)

**Comment by mapsam** [comment]
Looks like the sidebar can be customized with all pages! http://alabaster.readthedocs.io/en/latest/installation.html#sidebars

Updated would happen here: https://github.com/mapbox/mercantile/blob/1db90bfd00bcf564a4a307e120823de6b25743be/docs/conf.py#L182

**Comment by sgillies** [comment]
Thanks for the suggestion and research @mapsam ! 🙏

**Comment by mapsam** [comment]
Awesome! Nice work @sgillies
