### ISSUE TITLE
Error in documentation for bounding_tile

### ISSUE THREAD

**Issue by Mec-iS** [mapbox/mercantile#73]
Documentation for `mercantile.bounding_tile` states that the inputs have to be ordered as "South west east north"

https://github.com/mapbox/mercantile/blob/cd610ddbdf5910d3a68d8af8656a5c97575b66b5/mercantile/__init__.py#L387

instead in the tests and by using the code it is pretty evident that the order is "West south east north".

**Comment by sgillies** [comment]
@Mec-iS thanks for the report! I've fixed it in the master branch and I will issue a 1.0.1 release so that the changes will appear in https://mercantile.readthedocs.io/en/stable/api/mercantile.html.
