### ISSUE TITLE
Mercantile.tiles overshoots given the bounds of a tile

### ISSUE THREAD

**Issue by drwelby** [mapbox/mercantile#84]
If you feed the bounds of a given tile into `mercantile.tiles`, it returns four tiles:

```python
# get a tile
m = mercantile.Tile(76669,98727,18)
# get the tiles that cover the tile's bounds
list(mercantile.tiles(*mercantile.bounds(m), [18]))
```

```
 [Tile(x=76669, y=98727, z=18),
 Tile(x=76669, y=98728, z=18),
 Tile(x=76670, y=98727, z=18),
 Tile(x=76670, y=98728, z=18)]
```

**Comment by dnomadb** [comment]
Possibly relevant -- an epsilon is used in the CLI to allow round-tripping: https://github.com/mapbox/mercantile/blob/8971be31a7d9304409bd465b8292ab46dbe05c9e/mercantile/scripts/__init__.py#L282-L285

The challenge is that by definition, a given tile's (`[x, y, z]` lower right corner should == the upper left corner of tile `[x+1, y+1, z]`. By the same token, one might expect the same relationship with the lower right corner of `[x-1, y-1, z]`, but this tile is not returned here. However, I suspect that all of this is mercator math (https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_numbers_to_lon..2Flat.), and we take the calculated UL corners of `[x, y, z]` + `[x+1, y+1, z]` to create the bounding box.

I can't see a great way to fix this beyond arbitrarily adjusting the precision of the bounds such that the x+1/y+1 tiles are not returned. @drwelby any thoughts on an approach?

**Comment by drwelby** [comment]
The epsilon approach seems reasonable to me. The only question I have is if it should only be applied when all four bounding values are on mercator boundaries. I'm not sure whether a small bounding box that has one side coincident with a mercator boundary should return one tile or two.
