### ISSUE TITLE
Giving `fid=0` to `feature` gets overwritten.

### ISSUE THREAD

**Issue by jagill** [mapbox/mercantile#85]
In line [496](https://github.com/mapbox/mercantile/blob/5821d09ca20709e28b49aa2ea069f42acca27bb6/mercantile/__init__.py#L496) of `__init__.py`, it sets `feat['id']` to `fid` if `fid` is truthy.  This prevents you from passing in an `fid=0`, which would be natural from an `enumerate`.  The condition should be `if fid is None:`, I think.

Happy to send over a PR to fix this if you want.

**Comment by sgillies** [comment]
@jagill mercantile is more opinionated about feature ids than some other software. As it says in the docstring, we want strings. We're not failing in the integer case, but I think I would rather do that.
