### ISSUE TITLE
Should raise a ValueError when constructing an "invalid" tile?

### ISSUE THREAD

**Issue by alpha-beta-soup** [mapbox/mercantile#86]
```python
import mercantile
x, y, z = 10, 0, 0
tile = mercantile.Tile(x, y, z)
mercantile.bounds(tile)
# LngLatBbox(west=3420.0, south=-85.0511287798066, east=3780.0, north=85.0511287798066)
```
I find this surprising. I expected to see a ValueError or similar exception being raised if trying to build a tile like this: at zoom level 0, the only valid x and y values (to my mind) are 0 and 0.

If not an exception, then I would have expected that the tile bounds to be "rolled" back to a -180/180° degree range.

I simply find this behaviour surprising, I'm aware of how I can work around this in my own code.

Backing out the above result into a Tile again:

```python
list(mercantile.tiles(-3420.0, -85.0511287798066, 3780.0, 85.0511287798066, [0]))
# [Tile(x=0, y=0, z=0)]
```

**Comment by alpha-beta-soup** [comment]
Furthermore, a tile with a y coordinate out of range eventually produces a bounding box with latitude values that are outside of the extent defined by the Web Mercator projection.

```python
import mercantile
x, y, z = 0, 10, 0
tile = mercantile.Tile(x, y, z)
mercantile.bounds(tile)
# LngLatBbox(west=-180.0, south=-90.0, east=180.0, north=-90.0)
```

**Comment by sgillies** [comment]
Since Tile is a data class, there isn't harm in letting users create invalid ones, and maybe some weird but valid use cases. I prefer to have the functions that consume tiles do the validation on an as-needed basis.
