### ISSUE TITLE
improve documentation when passing in geojson

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mercantile#90]
can I add the advice from https://github.com/mapbox/mercantile/issues/64#issuecomment-337721427 to use `jq -s -c '.[0]'` when passing in GeoJSON to the cli tools? I can do a PR.

I got stuck on this with my pretty printed geojson, and only found the solution digging through closed tickets.

**Comment by sgillies** [comment]
@andrewharvey mercantile-shapes now has a `--seq` argument and that's the thing to use

```
$ echo "[106, 193, 9]" | mercantile shapes --indent 2 --seq | mercantile tiles 10
[212, 386, 10]
[212, 387, 10]
[213, 386, 10]
[213, 387, 10]
```

**Comment by andrewharvey** [comment]
Actually I was piping in GeoJSON directly to `mercantile tiles` to try to count tiles inside the GeoJSON.

This was so I could count tiles in a similar fashion to https://docs.mapbox.com/help/interactive-tools/offline-estimator/, which doesn't support arbitrary polygons, and since it's not on GitHub, I can't PR it, and turn to trusty mercantile instead. :wink:

**Comment by sgillies** [comment]
Gotcha. A doc update showing the use of jq would be perfect.
