### ISSUE TITLE
Problem arround 0

### ISSUE THREAD

**Issue by Djabx** [mapbox/mercantile#93]
Hi,

With this simple geojson (named as geo.geojson):

```geojson
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [
                            -1.109619140625,
                            50.968805734317804
                        ],
                        [
                            0.8074951171874999,
                            50.968805734317804
                        ],
                        [
                            0.8074951171874999,
                            51.82559340146247
                        ],
                        [
                            -1.109619140625,
                            51.82559340146247
                        ],
                        [
                            -1.109619140625,
                            50.968805734317804
                        ]
                    ]
                ]
            }
        }
    ]
}
```

I've done this: 

```
$ cat geo.geojson | jq -c . | mercantile bounding-tile
[0, 0, 0]
```

And it's not the write answer.

I've got mercantile: 1.0.4 with python 3.6.7

**Comment by Djabx** [comment]
Ok when reading the code I've seen this:

```comment
    NB: when the bbox spans lines of lng 0 or lat 0, the bounding tile
    will be Tile(x=0, y=0, z=0).
```

Strange assumption I suppose.
Anyway "it's normal".

**Comment by sgillies** [comment]
I must correct your "strange assumption" comment in case someone else comes across this issue and reads that as being the last word on the subject.

Draw a picture of the 4 zoom level 1 web mercator tiles. Now draw any rectangle that covers at least two of them. You will see that the zoom 0 tile is the only web mercator line that entirely contains the rectangle.

https://github.com/mapbox/tilebelt/issues/8 is concerned with boxes that just barely touch tile edges and where floating point precision becomes an issue. This is different from your situation.
